/**
 * Zsh completion script for the dojops CLI.
 * Exported as a string constant — printed by `dojops completion zsh`.
 */
export const ZSH_COMPLETION_SCRIPT = `#compdef dojops
# dojops zsh completion — generated by dojops completion zsh

_dojops_get_dynamic() {
  local type="$1"
  local result
  result=$(timeout 2 dojops --get-completions "$type" 2>/dev/null) || return
  echo "$result"
}

_dojops() {
  local -a commands global_flags

  commands=(
    'plan:Decompose goal into task graph'
    'generate:Generate DevOps config'
    'apply:Execute a saved plan'
    'validate:Validate plan against schemas'
    'explain:LLM explains a plan'
    'debug:Debug tools (ci)'
    'analyze:Analysis tools (diff)'
    'review:DevSecOps review with tool validation'
    'auto:Autonomous mode with self-repair'
    'inspect:Inspect config and session state'
    'agents:Manage specialist agents'
    'history:View execution history'
    'modules:Manage DevOps modules'
    'toolchain:Manage system toolchain'
    'scan:Security scan'
    'chat:Interactive AI DevOps session'
    'check:LLM-powered config quality check'
    'verify:Verify a configuration file'
    'provider:Manage LLM providers'
    'config:Configure provider, model, tokens'
    'auth:Authenticate with LLM provider'
    'serve:Start API server + dashboard'
    'status:System health diagnostics'
    'init:Initialize .dojops/ + scan repo context'
    'clean:Remove generated artifacts'
    'rollback:Reverse an applied plan'
    'cron:Manage scheduled jobs'
    'upgrade:Check for and install CLI updates'
    'help:Show help message'
    'completion:Generate shell completion scripts'
    'tools:Manage modules (deprecated alias)'
    'doctor:System diagnostics (alias for status)'
    'destroy:Remove artifacts (deprecated alias for clean)'
  )

  global_flags=(
    '--verbose[Verbose output]'
    '--debug[Debug-level output]'
    '--quiet[Suppress non-essential output]'
    '--no-color[Disable color output]'
    '--raw[Raw output without formatting]'
    '--non-interactive[Disable interactive prompts]'
    '--dry-run[Preview changes without writing files]'
    '--provider=[LLM provider]:provider:->providers'
    '--model=[LLM model override]:model:'
    '--fallback-provider=[Fallback provider chain]:provider:'
    '--agent=[Force specialist agent]:agent:->agents'
    '--module=[Force module]:module:->modules'
    '--tool=[Force module (alias)]:module:->modules'
    '--file=[Read prompt from file]:file:_files'
    '--profile=[Config profile]:profile:'
    '--temperature=[LLM temperature (0-2)]:temperature:'
    '--timeout=[Timeout in milliseconds]:timeout:'
    '--output=[Output format]:format:(table json yaml)'
    '--help[Show help message]'
    '--version[Show version]'
  )

  # Subcommand definitions
  local -a sub_debug sub_analyze sub_agents sub_history sub_modules sub_toolchain
  local -a sub_config sub_config_profile sub_auth sub_serve sub_chat sub_inspect
  local -a sub_provider sub_cron sub_completion

  sub_debug=('ci:Diagnose CI/CD log failures')
  sub_analyze=('diff:Analyze infrastructure diff for risk')
  sub_agents=('list:List agents' 'info:Show agent details' 'create:Create custom agent' 'remove:Remove custom agent')
  sub_history=('list:List execution history' 'show:Show execution detail' 'verify:Verify audit chain' 'audit:View audit entries' 'repair:Repair audit chain')
  sub_modules=('list:List modules' 'init:Scaffold a module' 'validate:Validate module' 'publish:Publish to Hub' 'install:Install from Hub' 'search:Search Hub' 'dev:Live validation')
  sub_toolchain=('list:List toolchain binaries' 'load:Load tool versions' 'install:Install tool' 'remove:Remove tool' 'clean:Clean toolchain cache')
  sub_config=('show:Show config' 'get:Get config value' 'set:Set config value' 'delete:Delete config value' 'validate:Validate config' 'reset:Reset config' 'profile:Manage profiles')
  sub_config_profile=('create:Create profile' 'use:Switch profile' 'delete:Delete profile' 'list:List profiles')
  sub_auth=('login:Authenticate' 'status:Show auth status' 'logout:Remove credentials')
  sub_serve=('credentials:Generate API key')
  sub_chat=('export:Export chat sessions')
  sub_inspect=('config:Inspect configuration' 'session:Inspect session state')
  sub_provider=('list:List providers' 'default:Set default' 'add:Add provider' 'remove:Remove provider' 'switch:Switch provider')
  sub_cron=('add:Add scheduled job' 'list:List jobs' 'remove:Remove job')
  sub_completion=('bash:Generate bash completions' 'zsh:Generate zsh completions' 'fish:Generate fish completions' 'install:Install completions')

  local curcontext="$curcontext" state line
  typeset -A opt_args

  _arguments -C \\
    $global_flags \\
    '1:command:->command' \\
    '2:subcommand:->subcommand' \\
    '3:sub-subcommand:->subsubcommand' \\
    '*::arg:->args'

  case $state in
    command)
      _describe -t commands 'dojops command' commands
      ;;
    subcommand)
      case $line[1] in
        debug) _describe -t sub 'subcommand' sub_debug ;;
        analyze) _describe -t sub 'subcommand' sub_analyze ;;
        agents) _describe -t sub 'subcommand' sub_agents ;;
        history) _describe -t sub 'subcommand' sub_history ;;
        modules|tools) _describe -t sub 'subcommand' sub_modules ;;
        toolchain) _describe -t sub 'subcommand' sub_toolchain ;;
        config) _describe -t sub 'subcommand' sub_config ;;
        auth) _describe -t sub 'subcommand' sub_auth ;;
        serve) _describe -t sub 'subcommand' sub_serve ;;
        chat) _describe -t sub 'subcommand' sub_chat ;;
        inspect) _describe -t sub 'subcommand' sub_inspect ;;
        provider) _describe -t sub 'subcommand' sub_provider ;;
        cron) _describe -t sub 'subcommand' sub_cron ;;
        completion) _describe -t sub 'subcommand' sub_completion ;;
      esac
      ;;
    subsubcommand)
      if [[ "$line[1]" == "config" && "$line[2]" == "profile" ]]; then
        _describe -t sub 'profile subcommand' sub_config_profile
      fi
      ;;
    providers)
      local -a provs
      provs=(\${(f)"$(_dojops_get_dynamic providers)"})
      _describe -t providers 'provider' provs
      ;;
    agents)
      local -a ags
      ags=(\${(f)"$(_dojops_get_dynamic agents)"})
      _describe -t agents 'agent' ags
      ;;
    modules)
      local -a mods
      mods=(\${(f)"$(_dojops_get_dynamic modules)"})
      _describe -t modules 'module' mods
      ;;
  esac
}

compdef _dojops dojops
`;
