import type { VerificationIssue } from "@dojops/sdk";

/**
 * Context7 Doc Auditor — validates generated content against Context7 documentation.
 *
 * Pure function, no LLM calls, no async, no side effects.
 * Extracts versioned references from generated content and cross-checks
 * against Context7 docs for outdated versions and deprecated syntax.
 *
 * Severity is always "warning" — never blocks execution.
 */

/** Technology-specific patterns for extracting versioned references. */
interface VersionPattern {
  /** Regex to extract version references. Must have a named group `ref` for the full reference. */
  regex: RegExp;
  /** How to build a search term from the match for checking against docs. */
  searchKey: (match: RegExpExecArray) => string;
}

const GITHUB_ACTIONS_PATTERNS: VersionPattern[] = [
  {
    // uses: actions/checkout@v4, uses: docker/build-push-action@v6
    regex: /uses:\s*(?<ref>[\w-]+\/[\w-]+@v\d+)/g,
    searchKey: (m) => {
      const ref = m.groups!.ref;
      // Extract action name: "actions/checkout@v4" → "actions/checkout"
      return ref.split("@")[0];
    },
  },
];

const DOCKERFILE_PATTERNS: VersionPattern[] = [
  {
    // FROM node:20-slim, FROM python:3.12
    regex: /FROM\s+(?<ref>[\w./-]+:[\w.-]+)/gi,
    searchKey: (m) => m.groups!.ref.split(":")[0],
  },
];

const TERRAFORM_PATTERNS: VersionPattern[] = [
  {
    // source = "hashicorp/aws" + version = "~> 5.0"
    regex: /source\s*=\s*"(?<ref>[\w-]+\/[\w-]+)"/g,
    searchKey: (m) => m.groups!.ref,
  },
];

/** Map of technology names to their version-extraction patterns. */
const TECHNOLOGY_PATTERNS: Record<string, VersionPattern[]> = {
  "GitHub Actions": GITHUB_ACTIONS_PATTERNS,
  Dockerfile: DOCKERFILE_PATTERNS,
  Docker: DOCKERFILE_PATTERNS,
  Terraform: TERRAFORM_PATTERNS,
  HCL: TERRAFORM_PATTERNS,
};

/** Extract all versioned references from generated content for a given technology. */
function extractVersionRefs(
  content: string,
  technology: string,
): { ref: string; searchKey: string; line: number }[] {
  const patterns = TECHNOLOGY_PATTERNS[technology];
  if (!patterns) return [];

  const results: { ref: string; searchKey: string; line: number }[] = [];
  const lines = content.split("\n");

  for (const pattern of patterns) {
    // Reset regex state for global patterns
    const regex = new RegExp(pattern.regex.source, pattern.regex.flags);
    for (let lineIdx = 0; lineIdx < lines.length; lineIdx++) {
      let match: RegExpExecArray | null;
      // Reset for each line since we use global flag
      regex.lastIndex = 0;
      while ((match = regex.exec(lines[lineIdx])) !== null) {
        results.push({
          ref: match.groups!.ref,
          searchKey: pattern.searchKey(match),
          line: lineIdx + 1,
        });
      }
    }
  }

  return results;
}

/** Patterns for detecting deprecated syntax mentions in Context7 docs. */
const DEPRECATED_MARKERS = [
  /deprecated[:\s]+["`']?(?<term>[^"`'\n,;.]+)/gi,
  /replaced\s+by\s+["`']?(?<term>[^"`'\n,;.]+)/gi,
  /no\s+longer\s+supported[:\s]+["`']?(?<term>[^"`'\n,;.]+)/gi,
  /use\s+["`'](?<term>[^"`']+)["`']\s+instead/gi,
];

/** Extract deprecated terms from Context7 documentation text. */
function extractDeprecatedTerms(docs: string): string[] {
  const terms: string[] = [];
  for (const pattern of DEPRECATED_MARKERS) {
    const regex = new RegExp(pattern.source, pattern.flags);
    let match: RegExpExecArray | null;
    while ((match = regex.exec(docs)) !== null) {
      const term = match.groups?.term?.trim();
      if (term && term.length > 2 && term.length < 100) {
        terms.push(term);
      }
    }
  }
  return terms;
}

/**
 * Extract version numbers mentioned in docs for a specific action/package/tool.
 * Returns the highest version number found, or null if none found.
 */
function findLatestVersionInDocs(docs: string, searchKey: string): string | null {
  // Escape the searchKey for regex
  const escaped = searchKey.replaceAll(/[.*+?^${}()|[\]\\]/g, String.raw`\$&`);

  // Look for patterns like "actions/checkout@v4", "searchKey@v5", "searchKey v5"
  const versionRegex = new RegExp(String.raw`${escaped}[@\s]v(?<ver>\d+)`, "gi");
  const versions: number[] = [];

  let match: RegExpExecArray | null;
  while ((match = versionRegex.exec(docs)) !== null) {
    versions.push(Number.parseInt(match.groups!.ver, 10));
  }

  if (versions.length === 0) return null;
  return `v${Math.max(...versions)}`;
}

export interface DocAuditResult {
  issues: VerificationIssue[];
}

/**
 * Audit generated content against Context7 documentation.
 *
 * Pure function — no I/O, no LLM calls.
 *
 * @param generatedContent - The raw content generated by the LLM
 * @param context7Docs - Documentation fetched from Context7 during generate()
 * @param technology - The technology name from the .dops skill (e.g. "GitHub Actions")
 * @returns Warning-level issues for outdated versions or deprecated syntax
 */
export function auditAgainstDocs(
  generatedContent: string,
  context7Docs: string,
  technology: string,
): DocAuditResult {
  if (!context7Docs || !generatedContent) {
    return { issues: [] };
  }

  const issues: VerificationIssue[] = [];

  // 1. Check for outdated version references
  const refs = extractVersionRefs(generatedContent, technology);
  for (const ref of refs) {
    const latestInDocs = findLatestVersionInDocs(context7Docs, ref.searchKey);
    if (!latestInDocs) continue;

    // Extract version from the reference
    const refVersionMatch = /@v(\d+)/.exec(ref.ref);
    if (!refVersionMatch) continue;

    const refVersion = Number.parseInt(refVersionMatch[1], 10);
    const docsVersion = Number.parseInt(latestInDocs.slice(1), 10);

    if (refVersion < docsVersion) {
      issues.push({
        severity: "warning",
        message: `Potentially outdated: ${ref.ref} — docs reference ${ref.searchKey}@${latestInDocs}`,
        line: ref.line,
        rule: "context7-version-check",
      });
    }
  }

  // 2. Check for deprecated syntax in generated content
  const deprecatedTerms = extractDeprecatedTerms(context7Docs);
  for (const term of deprecatedTerms) {
    // Only flag if the exact deprecated term appears in generated content
    // Use case-insensitive matching but require word-like boundaries
    const escaped = term.replaceAll(/[.*+?^${}()|[\]\\]/g, String.raw`\$&`);
    const termRegex = new RegExp(String.raw`\b${escaped}\b`, "i");
    if (termRegex.test(generatedContent)) {
      issues.push({
        severity: "warning",
        message: `Potentially deprecated syntax: "${term}" — check Context7 docs for alternatives`,
        rule: "context7-deprecated-check",
      });
    }
  }

  return { issues };
}
